### ISSUE TITLE
Using panicparse within a recover()

### ISSUE THREAD

**Issue by kofalt** [maruel/panicparse#10]
Hi! Cool library :smile:

To use pp as a library, I'd like to call it internally from within a recover block. The closest I found was `func ParseDump(r io.Reader, out io.Writer) ([]Goroutine, error)`, which I guess I could pass nil parameters to? Is there a more elegant option?

Thanks, and sorry if I missed something obvious.

**Comment by maruel** [comment]
panicparse effectively parses the output of [runtime.tracebackothers()](https://github.com/golang/go/blob/master/src/runtime/traceback.go#L692) and friends. It's called by [runtime.dopanic_m()](https://github.com/golang/go/blob/master/src/runtime/panic.go#L606).

None of this code is accessible externally. So your best bet would be to do something similar and construct the objects [stack.Goroutine](https://godoc.org/github.com/maruel/panicparse/stack#Goroutine) manually via a snapshot of the system, likely with [runtime.GoroutineProfile()]https://golang.org/pkg/runtime/#GoroutineProfile], then call stack.Bucketize() and finally print it out. The code to print out is not externalized yet either, as I hadn't decided the proper API (Issue #8). Still, runtime.GoroutineProfile() doesn't return all the information so I don't know how useful this would be in practice. This is definitely worth investigating if there's a way to gather caller information and goroutine state at the time of the snapshot, I recommend you to read the sources in src/runtime/*.go to find whatever can be gleaned from the public APIs.

**Comment by maruel** [comment]
Unless you know a way to implement this safely, I don't expect this to be feasible. As such, I'll close the issue.
