### ISSUE TITLE
Improve color palette

### ISSUE THREAD

**Issue by maruel** [maruel/panicparse#11]
Facts:
- Some Go users use terminal with white background. I suspect this is mostly caused by OSX's Terminal defaults. I expect little to no Linux and Windows users to use white background.
  - Terminal with white background makes yellow and light gray hard to read: http://i.imgur.com/WqNVjfh.png
- Some people cannot distinguish green-red. This is a bigger non-self inflected problem.

Options:
  1. Make the color palette configurable via an environment variable.
  1. Force the background to be black. This would look like hell but would be readable yet very annoying.
  1. Try to read the background color and switch color table dynamically (no idea how to achieve this).
  1. Change the current colors to use a palette that is both readable with black and white backgrounds.

I think option 1 is preferable but it still has the drawback of not working out of the box, requiring reading the help page, then taking action to make the change permanent. This is clumsy and annoying.

So in the meantime, option 4 is more sensible. I need to play with both 256 and 16 colors terminals to ensure I do not make things worse.

Reference: https://news.ycombinator.com/item?id=10634503

**Comment by lmorg** [comment]
You're probably already aware of this, but POSIX terminals do have a emphasis and a regular colour which will be matched with a sympathetic, readable, colour on the terminal emulator. Which should save you having to pick specific colours out. Not sure if the Windows terminal (cmd.exe) also supports the same though.

For what it's worth, I run white terminals in Linux and most of the IT department at my work run Windows with white PuTTY sessions. So there are quite a few of us annoying folk with non-OSX white terminals hehehe

**Comment by maruel** [comment]
Once PR #13 is merged, I'll look into this unless someone preempts me.

I'm not sure what you are referring about the emphasis colors. I realized I'm accidentally using high numbered colors (90+) but that's only because it happened they were the most eye pleasing while playing with different colors while using 2 intensity levels and that's what github.com/mgutz/ansi defaults to. I'm not sure why it doesn't use bold for high intensity.

Options:
- Use DefaultFG(39) + bold(1) instead of LightWhite (97)
- Use color+bold(1) everywhere instead of high color(90+)

**Comment by maruel** [comment]
@lmorg now that PR #13 is merged, you can send a PR if you want. Otherwise I'll try to look at it before EOY or something.

**Comment by maruel** [comment]
Please test the branch `colors_white_background` and report if you prefer the colours. I plan to squash the branch and commit to master in the coming days.
