### ISSUE TITLE
Support fish shell

### ISSUE THREAD

**Issue by lthibault** [maruel/panicparse#15]
Fish doesn't seem to like the `| &pp` syntax.  Is there an equivalent means of using panicparse?

**Comment by maruel** [comment]
Here's what I found with my favorite web engine as the first hit for `fish redirect`:
http://fishshell.com/docs/current/tutorial.html#tut_pipes_and_redirections
> stdin and stdout can be redirected via the familiar < and >. Unlike other shells, stderr is redirected with a caret ^

I'm not sure what you are asking for, do you want me to document this in README.md or was this is simply a request for general fish usage help?

**Comment by lthibault** [comment]
@maruel Thanks for the quick reply.  I indeed intended this as a request to update the readme.  Thanks for the info!
