### ISSUE TITLE
Output modification fails on a Gin application

### ISSUE THREAD

**Issue by moberemk** [maruel/panicparse#17]
I tried to set this up with my company's Gin application and it...just sort of failed. All debug output is gone and the only message resulting from `panic` output is a
`bufio.Scanner: token too long ` error.  For context, here's (a shortened by ~15 frames and obfuscated version of) what normally goes to the console:

```
goroutine 55 [running]:
main.recovery(0xc8201f6310)
	/appdir/middleware.go:40 +0x165
main.(*DB).Update(0xc8202d1860, 0x78e0c0, 0xc82006cd00, 0xc820369440, 0xc8201e5680)
	/appdir/db.go:150 +0x1a19
main.UpdateAccountHandler(0xc8201d4430)
	/appdir/account_handlers.go:134 +0x326
main.InjectContext.func1(0xc8201664d0)
	/appdir/context.go:52 +0x61
created by net/http.(*Server).Serve
	/appdir/server.go:1910 +0x3f6
  type=stack-trace
```

Admittedly we've got our own output systems in place instead of just a standard `panic` call, but the output format doesn't seem different enough to cause a major issue...thoughts?

**Comment by maruel** [comment]
Hard to say, I've never used gin (assuming you are referring to https://github.com/gin-gonic/gin).
From a quick glance at src/bufio/scan.go, IIUC bufio.ErrTooLong can happen when the line is over bufio.MaxScanTokenSize.
https://github.com/golang/go/blob/master/src/bufio/scan.go#L64
https://github.com/golang/go/blob/master/src/bufio/scan.go#L70
https://github.com/golang/go/blob/master/src/bufio/scan.go#L186

I guess we could increase the buffer length to be >64kb. Can you send a PR?

**Comment by moberemk** [comment]
You can't actually increase that though can you? It's defined as a constant; not sure how you'd get around this limit without maybe having to change the way that the reader operates at least a little.

**Comment by c2h5oh** [comment]
@moberemk yes you can. You can provide your own buffer of any size using `scan.Buffer(`

**Comment by moberemk** [comment]
Okay so that commit DOES solve the token too long error...and then causes a new issue. All I'm getting in the terminal is this line: `time="2015-12-28T13:39:26-05:00" level=error msg="{OUTPUT}" type="stack-trace"` where `{OUTPUT}` is just the original go stack trace but with two alterations:

1. All newline and tab characters are converted to ASCII `\n` and `\t` instead of being indents and newlines
2. Uncountable numbers of `\x00` (ASCII NULL) characters appended to the end of the output

But hey at least it's parsing now; now I wonder if all those extra null characters were what caused me to run into the issue initially? Unescaped, they wouldn't appear in the terminal output but if the scanner did pick them up then maybe it made the captured text too big for the buffer.

**Comment by maruel** [comment]
About 1) `\n` and `\t`, you mean that they are output escaped? Is that gin doing that? If so, I'm not sure what pp could help here. What you describe seems to be part of an attribute of a XML node but C like escaping is unexpected to me.
About 2) having a repro would help. Please file a separate issue for this.

**Comment by moberemk** [comment]
I mean output-escaped yeah. Not totally sure where that's coming from
exactly, I don't think it's Gin since that normally doesn't escape the
output--looks like that is probably coming from whatever's wrapping the
output for some reason? I'll have to dig into it more but something weird
is happening between the normal error output and pp

If I can figure out a good repro case I'll file a new issue then.

**Comment by moberemk** [comment]
For future reference: this issue has been confirmed as being caused by an excess of null bytes at the end of the stack trace. The error handling was originally done like this:

```go
buf := make([]byte, 1<<16)
runtime.Stack(buf, false)

stackTrace := fmt.Sprintf("%s", buf)
```

and the problem was resolved by trimming the output of null bytes like this:

```go
buf := make([]byte, 1<<16)
runtime.Stack(buf, false)

trace := bytes.Trim(buf, "\x00")

stackTrace := fmt.Sprintf("%s", trace)
```

**Comment by maruel** [comment]
That is incorrect, you should do:

```
buf := make([]byte, 1<<16)
trace := fmt.Sprintf("%s", buf[:runtime.Stack(buf, false)])
```

1<<16 is a bit much to allocate on a crash, you should preallocate it if possible or reduce its size.

**Comment by moberemk** [comment]
Oh that's way more concise, thanks for pointing it out!
