### ISSUE TITLE
the rabbit

### ISSUE THREAD

**Issue by magicalbanana** [maruel/panicparse#22]
I want to know how your CLI has a rabbit. :laughing:

**Comment by maruel** [comment]
The character is U+1F407:🐇. It renders very differently on OSX vs on Ubuntu, the screenshot was taken on Ubuntu. Add it to your PS1 or whatever you use to set your shell.

**Comment by maruel** [comment]
What you want is Noto Sans Emoji: https://www.google.com/get/noto/#emoji-qaae
