### ISSUE TITLE
Implement "-race" error parser

### ISSUE THREAD

**Issue by azr** [maruel/panicparse#27]
Hey there !

I know It's not in the name but.
It would be nice also for panicparse to do the same for any `-race` hit.

**Comment by maruel** [comment]
Want to help with this?

**Comment by azr** [comment]
Oh, yes ! but I have short time 😅 how could I do this ?

**Comment by sectioneight** [comment]
I would also like to see this happen. IMHO they should be separate utilities (git repos) sharing a common parsing package. I may have some time to contribute to this soon.

**Comment by sectioneight** [comment]
Hmm, on second thought, there are some  compelling arguments to leaving it here and calling it "goroutineparse" or something. @maruel what do you think?

**Comment by maruel** [comment]
I'd prefer to have a single CLI. Taking a very simple example:
```go
package main
func main() {
  for i := 0; ; i++ {
    go func() { i++ }()
  }
}
```

I get the following output:
```
go run -race data_race.go
==================
WARNING: DATA RACE
Read at 0x00c42009e000 by goroutine 5:
  main.main.func1()
      /path/to/data_race.go:5 +0x3b

Previous write at 0x00c42009e000 by main goroutine:
  main.main()
      /path/to/data_race.go:4 +0xa7

Goroutine 5 (running) created at:
  main.main()
      /path/to/data_race.go:5 +0x7d
==================
^Csignal: interrupt
```

The code lives at https://go.googlesource.com/go/+/go1.8/src/runtime/race/ but is precompiled binaries. 

They are built with https://github.com/golang/build/blob/master/cmd/racebuild/racebuild.go

which leads to https://github.com/llvm-mirror/compiler-rt/blob/master/lib/tsan/rtl/tsan_report.cc#L459
(I failed to find an online source browser at llvm.org)

Parsing would required a separate state machine but it can still live in the same project based on different triggers.

**Comment by maruel** [comment]
Renamed the issue, created tool "panic" to reliably generate an output, this requires some regexps and likely some API breaking changes in stack but this is fine, it's worth a v2.

**Comment by maruel** [comment]
It's pretty much implemented now. I'll make it official in v2.0.0, you can try v2.0.0-alpha1 in the meantime.

**Comment by azr** [comment]
Super nice !
