### ISSUE TITLE
Color does't work well on Windows

### ISSUE THREAD

**Issue by cosiner** [maruel/panicparse#4]
There is no color on babun(cygwin), and only red on windows cmd prompt.
![babun](https://cloud.githubusercontent.com/assets/7279362/7486153/3e0f7134-f3d3-11e4-8f1f-d3094bfc3c21.png)
![cmd](https://cloud.githubusercontent.com/assets/7279362/7486156/46be4f8a-f3d3-11e4-9bd9-4e8024f5e764.png)

**Comment by maruel** [comment]
It's a limitation of github.com/shiena/ansicolor, please improve this project.

**Comment by maruel** [comment]
Reopening since it's worth fixing and fixing github.com/shiena/ansicolor may or may not be the best option.
