### ISSUE TITLE
feature request: windows eventlog support with golang.org/x/sys/windows/svc/eventlog

### ISSUE THREAD

**Issue by fpawel** [maruel/panicparse#40]
Heya! Thank's for good tool!
It would be nice to write panic in a windows system journal like this:
```
app 2>&1 | pp --eventlog="app name" --html="panic.html"
```
Any plans for subj? I would create a pull request if it makes sense

**Comment by maruel** [comment]
You mean that it would work as a filter that would generate event logs whenever a panic is detected? I feel the use case for this is for continuously running applications, so I think it would warrant a separate executable under ./cmd/. wdyt?

**Comment by maruel** [comment]
Closing due to lack of reply from the reporter.
