### ISSUE TITLE
TestAugment fails on 1.11

### ISSUE THREAD

**Issue by twmb** [maruel/panicparse#42]

**Comment by maruel** [comment]
Thanks will look tomorrow.

**Comment by twmb** [comment]
No problem; I tried looking into it but I had no idea what was up offhand (otherwise I would have had a few more details).

**Comment by maruel** [comment]
Easily reproduced. Dang. At least I'm glad I wrote a test. :)  I have the feeling issue #2 should be fixed along the way.

**Comment by maruel** [comment]
If someone has some time to fix this, they will have my eternal gratitude. I'll try to get this done eventually but Real Life caught me.

**Comment by maruel** [comment]
Still looking for help if someone wants to tackle this.

**Comment by maruel** [comment]
It took a while but I ran a bisect on Go and found that https://go.googlesource.com/go/+/c08b01ecb4488fb3a95fd5cc7baa8b31812e7b76 is the commit that made the regression.

I'll add a workaround in the test, which commit description will contain what I did to do the bisect. I think I'll file a bug too.

The only issue that refers to this commit is https://github.com/golang/go/issues/25776.

**Comment by maruel** [comment]
Commented on https://go-review.googlesource.com/c/go/+/116656/ in case someone wonders about this in the future.
