### ISSUE TITLE
How to parse a stacktrace?

### ISSUE THREAD

**Issue by derekperkins** [maruel/panicparse#50]
There's a beautiful looking `Stack` struct that I'm hoping to be able to use, but I can't figure out how to generate it from a library. https://pkg.go.dev/github.com/maruel/panicparse/v2/stack#Stack

This is what I was expecting to find, but I can't see anything public that returns a `Stack`

```
// Library function
func ParseStack(stackBytes []byte) *Stack

// Usage
myStack := stack.ParseStack(debug.Stack())
```

My use case is that we wrap errors as we move up the stack and attach contextual data to each frame. We have our own internal stacktrace parser, but are hoping to swap it out for panicparse. Is this something you would like to support?

**Comment by maruel** [comment]
Humm, I focused on the advanced usages in the examples at https://pkg.go.dev/github.com/maruel/panicparse/v2/stack but forgot to add a trivial one. A simple example would be (pseudo code, untested):

```
func parseStack(data []byte) (*stack.Stack, error) {
  s, _, err := stack.ScanSnapshot(bytes.NewReader(data), ioutil.Discard, stack.DefaultOpts())
  return s, err
}
```

**Comment by derekperkins** [comment]
Thanks for the response. I'm looking for a stack, not a snapshot. Is this pseudocode essentially what would need to happen? Would you be open to a PR that exposed this in the api directly?

```
func parseStack(data []byte) (*stack.Stack, error) {
  s, _, err := stack.ScanSnapshot(bytes.NewReader(data), ioutil.Discard, stack.DefaultOpts())
  if err != nil {
      return err
  }
  return s.Goroutines[0].Signature.Stack, nil
}
```
