### ISSUE TITLE
panicparse ignores control-C

### ISSUE THREAD

**Issue by bboreham** [maruel/panicparse#70]
This was puzzling to me when trying it out - if you don't supply a filename it just hangs and can't be interrupted.
The behaviour was added in a0eb0cee87d7cad0b22421baf899a09380d36fce, but I don't follow the explanation.
I can understand ignoring Ctrl-\\, which was added later.

**Comment by maruel** [comment]
The reason is that you can Ctrl-C out the test, hence `go test |& pp` does the right thing.

**Comment by bboreham** [comment]
Still don’t follow. Why do you want pp to keep running after the test program has died?

**Comment by maruel** [comment]
Err, I meant SIGQUIT is what we care about, more than SIGTERM. See https://github.com/maruel/panicparse#investigate-deadlock for a use case.

**Comment by bboreham** [comment]
OK, but the code ignores both.  My issue is that the code ignores Control-C.

**Comment by maruel** [comment]
Fair point, it's probably fine to only handle SIGQUIT and not SIGINT. We would have to adapt it on Windows;

For context; https://github.com/maruel/panicparse/blob/main/internal/main.go#L291

**Comment by bboreham** [comment]
I'm happy to submit a PR to remove `os.Interrupt` from the list.
What's different on Windows?

**Comment by maruel** [comment]
Windows doesn't have a concept of signals in the way POSIX does. This require some manual testing directly on Windows.

**Comment by maruel** [comment]
Closing as WAI. I guess it could be made an option but you haven't provided a use case yet.
