### ISSUE TITLE
Add aliasing hint to `/usr/bin/pp` section?

### ISSUE THREAD

**Issue by jtagcat** [maruel/panicparse#71]
https://github.com/maruel/panicparse#if-you-have-usrbinpp-installed

I'd add a hint to the README that btw you can do `alias p=panicparse`/`alias gp=panicparse` (go panic), or anything else.

It seems obvious, but people might not come to the idea right away.

Thoughts? yes/no?

I can make PR. /assign self

**Comment by maruel** [comment]
Sure
