### ISSUE TITLE
parsepanic parsing issues on Go 1.18

### ISSUE THREAD

**Issue by asahasrabuddhe** [maruel/panicparse#79]
We use `panicparse` as a library to parse the panic and send the stack trace on Slack / Email etc. Recently, we noticed that our stack traces are empty. We saw this error from `panicparse` - `failed to parse int on line: "server/interactors.(*Message).FindByMessageID(0xc0006b3990, {0xc001cc6161?, 0x2?})`

Any idea on what could be happening here?

**Comment by maruel** [comment]
I saw that too but didn't have time to fix. The state machine has to be updated.

**Comment by asahasrabuddhe** [comment]
@maruel I will try to take a look tomorrow to see if I can do a PR

**Comment by asahasrabuddhe** [comment]
> Had [426572b](https://github.com/maruel/panicparse/commit/426572b136fab7566a522925f6a3b9f61b9683a2) helped? I forget.

Sorry for the delayed reply. This actually fixes the issue. Thanks a lot @maruel !
