### ISSUE TITLE
Opening "internal" to the world; export writer as an API

### ISSUE THREAD

**Issue by rshmelev** [maruel/panicparse#8]
Hey, i'm building some golang app supervising software and found your stacktracing project interesting.
Is it possible to get rid of "internal" package (e.g. rename it to "reallyinternal") so I'll be able to import it and use its functions?

**Comment by maruel** [comment]
Which part in particular? I made it internal intentionally; I want to keep the possibility to refactor it as needed. 
The files are short, at worst copy paste (with attribution and license).

**Comment by rshmelev** [comment]
Thanks for reply :)

So there are two things i'd like to get,  
one is Process (to actually get beautiful stack trace)
and the second one is NewAnsiStripper (to get rid of color)
I'd like to be able to import these as library.

**Comment by maruel** [comment]
I didn't feel the current design was API worthy yet without some refactoring, in particular if you'd start using it I'd likely break the API once I (or someone else) start refactoring it. Maybe it's fine but I don't have a good feeling about it yet.

So for now I'd recommend (as stated above) to either copy or reimplement in the way you prefer. FTR, my use case was to reimplement it inside something like https://github.com/derekparker/delve.

Or you can send a pull request with some refactoring, I may accept it.

**Comment by maruel** [comment]
FTR, I still want to make it a public API, I just haven't taken the time yet. Until it's done I still recommend copy-paste. Hopefully I'll be able to set aside time to finish that before EOY. Sorry for not accepting contributions about this, I don't want to be stuck maintaining an API I don't like.

**Comment by rshmelev** [comment]
Okay, no problem :)

**Comment by pyros2097** [comment]
Yes Please! ++1 :dancer:

**Comment by jpillora** [comment]
+1

**Comment by maruel** [comment]
My plan is to migrate Palette, DefaultPalette and Process (but not Main) from https://godoc.org/github.com/maruel/panicparse/internal into https://godoc.org/github.com/maruel/panicparse/stack.

Please promptly comment on any idea to improve the current implementation to reduce the risk of follow up breaking change. Thanks.

**Comment by maruel** [comment]
Bueller?

**Comment by pyros2097** [comment]
I don't know much of how it is implemented or being used right now but hey go right ahead buddy. I tried to use it but then id didn't work. Then I tried to integrated it manually into the logger which we using log15 but then there always seemed like there was some conflict with the loggers output and panicparse's output and nothing changed. So I think maybe with this we should be able to output pretty stack traces with the logger and email them. And btw in go 1.6 I think they are by default only going to show the goroutine that crashed not the others.

**Comment by pyros2097** [comment]
Great Work. Now I can now haz proper panic stack traces. I guess there should be an example on how to use this exposed stack. Took some digging to find out how to do this.
And also I think exposing a default palette might also be useful just like other go libs (ex: apex/log) otherwise I have to add some more libs to my vendor for colors.


![screenshots](https://cloud.githubusercontent.com/assets/1687946/13215567/4408fb98-d97c-11e5-8cf7-dcd1fd32ffd2.png)

**Comment by pyros2097** [comment]
Is there someway to format this using html tags because now it comes like this in my mail whenever a panic occurrs in out servers
```
panic recover interface conversion: interface {} is nil, not map[string]interface {} stack trace 11963 bytes [1;35m1: running [90m [Created by http.(*Server).Serve @ server.go:2137] [39m [m [1;39mserver [39m [mmain.go:345 [1;31mServe.func3.1.1 [39m [m(0x7f2b24e348a8, 0xc8202fa820, #8, 0xc820e0db60, 0xc82052b9b0) [39m [m [1;39m [39m [mpanic.go:426 [32mpanic [39m [m(0xbd2b00, 0xc82030d0a0) [39m [m [1;39mhelpers [39m [mmain.go:108 [1;31mHandlePanic [39m [m(0xc82040fdb0) [39m [m [1;39m [39m [mpanic.go:426 [32mpanic [39m [m(0xd0d280, 0xc820dd5dc0) [39m [m [1;39mcatalyst [39m [mgame.go:325 [31mGameMutationInit.func1 [39m [m(0xc82015ea80, #10, 0xa, #11, 0x1, 0x1, #14, #3, 0x7f2b24e417b8, #5, ...) [39m [m [1;39mrelay [39m [mmutation.go:78 [31mMutationWithClientMutationID.func1 [39m [m(0xbd0700, #13, 0xc82015ebd0, #10, 0xa, #11, 0x1, 0x1, #14, #3, ...) [39m [m [1;39mgraphql [39m [mexecutor.go:510 [31mresolveField [39m [m(#7, #5, 0xbd0700, #13, #11, 0x1, 0x1, 0, 0, 0xd0c000) [39m [m [1;39mgraphql [39m [mexecutor.go:200 [31mexecuteFieldsSerially [39m [m(#7, #5, 0xbd0700, #13, #2, #2) [39m [m [1;39mgraphql [39m [mexecutor.go:156 [31mexecuteOperation [39m [m(#7, 0xbd0700, #13, 0x7f2b24e4a8a8, 0xc8203315e0, 0) [39m [m [1;39mgraphql [39m [mexecutor.go:54 [1;31mExecute [39m [m(#4, #5, #6, 0, 0, 0, 0xbd0700, #13, 0xc820df2390, 0, ...) [39m [m [1;39mgraphql [39m [mgraphql.go:42 [1;31mDo [39m [m(#4, #5, #6, 0, 0, 0, 0xc820331110, 0x64, #13, 0xc820337dd0, ...) [39m [m [1;39mserver [39m [mmain.go:586 [31mServe.func6 [39m [m(#8, 0, 0) [39m [m [1;39mserver [39m [mmain.go:508 [1;31mServe.func5.1 [39m [m(#8, 0, 0) [39m [m [1;39mserver [39m [mmain.go:381 [1;31mServe.func4.1 [39m [m(#8, 0, 0) [39m [m [1;39mserver [39m [mmain.go:363 [1;31mServe.func3.1 [39m [m(#8, 0, 0) [39m [m [1;39mecho [39m [mecho.go:575 [1;31m(*Echo).ServeHTTP [39m [m(0xc82032c000, #15, #12, #1) [39m [m [1;39mhttp [39m [mserver.go:2081 [1;32mserverHandler.ServeHTTP [39m [m(#9, #15, #12, #1) [39m [m [1;39mhttp [39m [mserver.go:1472 [32m(*conn).serve [39m [m(0xc8202e1980) [39m [m 1: IO wait [39m [m [1;39mnet [39m [mnetpoll.go:160 [32mruntime_pollWait [39m [m(#65, 0x72, 0) [39m
```

**Comment by pyros2097** [comment]
Figured it out. Now I'm using this to conver ansi terminal text to html https://github.com/buildkite/terminal
