### ISSUE TITLE
TestAugment fails on all architectures other than amd64

### ISSUE THREAD

**Issue by anthonyfok** [maruel/panicparse#80]
All tests TestAugment passes on the amd64 architecture, but some of the tests would fail on all other architectures.

For example, with the recent Debian builds of panicparse 2.2.2-1:

| Test | Architectures on which the test failed |
| ---------- | ---------- |
| TestAugment/0-local_function_doesn't_interfere | arm64, armel, armhf, ppc64el, riscv64 |
| TestAugment/1-func | armel, armhf |
| TestAugment/12-string | arm64, armel, armhf, ppc64el, riscv64 |
| TestAugment/13-string_and_int | arm64, armel, armhf, ppc64el, riscv64 |
| TestAugment/16-error_unnamed | arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, riscv64, s390x |
| TestAugment/24-argument_offsets_partially_too_large | armel, armhf, i386, mipsel |
| TestAugment/25-argument_offsets_entirely_too_large | armel, armhf, i386, mipsel |

IIRC, the mapping from Debian architecture names to GOARCH are as follows:
* armel and armhf ⇒ `GOARCH=arm`
* i386 ⇒ `GOARCH=386`
* mips64el ⇒ `GOARCH=mips64le`
* mipsel ⇒ `GOARCH=mipsle`
* ppc64el ⇒ `GOARCH=ppc64le`

Screen capture of overview of Debian build status for panicparse (<https://buildd.debian.org/status/package.php?p=panicparse>):

![image](https://user-images.githubusercontent.com/1274764/174602644-7be45b1a-fe37-4b54-9ce3-4efcf932fd2f.png)

Thanks!

**Comment by maruel** [comment]
Thanks for the report, I've been working on it past weekend. I was focusing on i386 but I'll make it skip on other CPU architectures too.

**Comment by anthonyfok** [comment]
@maruel Wow, that was very quick!  Thank you so much!

> is there any way I can confirm this is good enough before I tag a new release?

I'd be happy to test it with Debian infrastructure by including 15e67c5 and other related commits as debian/patches/*.patch, and upload a 2.2.2-2 to Debian and see how it goes.  I'll report the results in a day or two (or three).  :-)

**Comment by maruel** [comment]
Ok thanks, keep me updated and I'll make another commit to skip any test case I would have missed in the first time, then I'll do a v2.3.0 release.

**Comment by anthonyfok** [comment]
Here is the test result with panicparse 2.2.2+git20220620.15e67c5-1:

![image](https://user-images.githubusercontent.com/1274764/174749704-14e532a6-cd83-4680-b636-37011d0a81c7.png)

| Test | Architectures on which the test needs to be skipped |
| ---- | --------------------------------------------------------- |
| TestAugment/18-float64 | armel, armhf, i386, mipsel (GOARCH `386`, `arm`, `mipsle`) |

This following patch

```patch
--- a/stack/source_test.go
+++ b/stack/source_test.go
@@ -606,9 +606,9 @@ func TestAugment(t *testing.T) {
 			func f(v float64) {
 				panic("ooh")
 			}`,
 			true,
-			goarchList{"386"},
+			goarchList{"386", "arm", "mipsle"},
 			Stack{
 				Calls: []Call{
 					newCallSrc(
 						"main.f",
```

was applied to panicparse 2.2.2+git20220620.15e67c5-2 which built and tested successfully on all relevant architectures, see https://buildd.debian.org/status/package.php?p=panicparse

Many thanks!

**Comment by maruel** [comment]
Thanks for the update. I'll wait for you to confirm that the tests pass unmodified and I'll release v2.3.0.

**Comment by anthonyfok** [comment]
It's good to go: 2.2.2+git20220621.c95a0e4-1 gives green light on all relevant architectures at https://buildd.debian.org/status/package.php?p=panicparse

Thanks for fixing the issue!
