### ISSUE TITLE
How do I use it in a web-project as panic recovery middleware

### ISSUE THREAD

**Issue by pjebs** [maruel/panicparse#81]
How do I use this package as "middleware" so if a panic occurs, I can display the nice webpage that this package offers.

**Comment by maruel** [comment]
Do you mean as a http.Handler?

**Comment by pjebs** [comment]
Yes, but immediately after a panic:

https://github.com/urfave/negroni/blob/master/recovery.go#L160

This package displays a decent looking stack trace and also the actual panic message.

**Comment by maruel** [comment]
Ok I'll add an example.

**Comment by maruel** [comment]
Would this solve your issue?
https://github.com/maruel/panicparse/blob/example_middleware/stack/example_test.go#L187

**Comment by pjebs** [comment]
Thanks for that. I don't see the pretty html page in your example though.

**Comment by maruel** [comment]
https://pkg.go.dev/github.com/maruel/panicparse/v2@v2.3.2-0.20221019195939-fc0be8ea249e/stack#example-package-HttpHandlerMiddleware

The example will be live as soon as I push the next git tag.

I believe this information should be sent to logs. I don't think printing the stack to the user is a good idea, at least not without strong access control. But if people want to do that, sure, go for it! I just prefer to not make an example for this. There's already [webstack](https://pkg.go.dev/github.com/maruel/panicparse/v2/stack/webstack) that shows how to do something similar.

As a matter of fact, the code you pointed to in recovery.go is functionally wrong. The only way it could be done is if it were buffering a temporary http.ResponseWriter, and only flushing it when the handler returned. The current code will fail at line 161 as WriteHeader() will ignore the status if data was already written (that's how HTTP works) and the stack data will just be appended to whatever was already streamed to the user. That's bad.

**Comment by pjebs** [comment]
It's usually done only during local development.

**Comment by pjebs** [comment]
![Screen Shot 2022-10-20 at 9 58 09 am](https://user-images.githubusercontent.com/5377970/196820072-e570a076-06b2-439d-a591-1f0bad4146f0.png)

![image](https://user-images.githubusercontent.com/5377970/196820364-6244a25c-55dc-420f-97f3-1d06bf503eb9.png)

Using the Fiber snippet: Is there an option I can use to bypass say the first 6 items (the intention is to get rid of the red section)

**Comment by maruel** [comment]
What you'd like is to trim some of the items. I never thought about this needs, it sounds reasonable. In practice, you could do:

```go
// Number of call items to remove from the stack.
N := 5

s, err := snapshot(64 << 20, stack.DefaultOpts())
// TODO: handle err

w.Header().Set("Content-Type", "text/html; charset=utf-8")
// Remove the N stack traces in s:
s.Goroutines[0].Signature.Stack.Calls = s.Goroutines[0].Signature.Stack.Calls.
[N:]
a := s.Aggregate(stack.AnyPointer)
a.ToHTML(w, "")
```

and copy paste snapshot() from https://github.com/maruel/panicparse/blob/main/stack/webstack/webstack.go#L96

That's what https://pkg.go.dev/github.com/maruel/panicparse/v2/stack#example-package-HTML is about.

In practice you want to not hardcode to N because of inlining, so you probably want to key on function name or something similar.
