### ISSUE TITLE
Change output order to: file package func

### ISSUE THREAD

**Issue by sqp** [maruel/panicparse#85]
Hello, thanks for your nice project
I think the output could be more intuitive if you switch the order from
`package     file     func`
to
`file         package func`

with format `%-20s %20s %s` to group and align package with func.
In go, we're trained to remember our types as `package.Symbol` so this would help instantly read calls origin.

Here's an example (just edited image):

![panicparse_output](https://github.com/maruel/panicparse/assets/281250/6b6542cf-296a-4cba-a370-5d89ef363628)

**Comment by maruel** [comment]
It's about gradual context. Without the package first, one cannot know which directory to look for the file. Your example only works for trivial use cases with a limited number of packages participating in the stack trace. It breaks down in complex use cases. As such, I don't feel it's a good idea at the moment.
