### ISSUE TITLE
More aggressive deduplication

### ISSUE THREAD

**Issue by cespare** [maruel/panicparse#9]
Hi, thanks for the great tool!

I took a large (20k lines) goroutine dump from a server and I used panicparse to analyze it. Unfortunately panicparse still emits many thousands of lines because lots of goroutines that are the same for my purposes cannot be deduplicated.

I dug into it more and I found two specific issues:

1. Panicparse compares argument values and if it doesn't think they're pointers, it wants the values to be the same. For my purposes, I really don't care about function args; I want two goroutines to be deduped if they have the same stack trace.

  In case it helps, here are two lines from two different goroutines that caused them to not be deduped (this is deep in `net`'s inner workings, far away from my own code):

      io.copyBuffer(0x7fa5add90238, 0xc820106aa0, 0x7fa5addd01d8, 0xc820106a60, 0xc820166000, 0x8000, 0x8000, 0x38bd, 0x0, 0x0)
      io.copyBuffer(0x7fa5add90238, 0xc820028220, 0x7fa5addd01d8, 0xc820152148, 0xc820a80000, 0x8000, 0x8000, 0x98d, 0x0, 0x0)

  My quick hack was to modify my local copy of stack.go to consider two `Args` to be similar if they have the same number of args (without looking at the args):

  ``` go
  func (a *Args) Similar(r *Args) bool {
    return a.Elided == r.Elided && len(a.Values) == len(r.Values)
  }
  ```

2. If a goroutine has been blocked for a long time on e..g a channel op or IO, it prints something like

        goroutine 134103 [chan send, 609 minutes]:

  or

      goroutine 134227 [IO wait, 747 minutes]:

  A difference in # of minutes causes two goroutines not to be deduped. My quick hack here was to modify my trace file with a quick `s/\d+ minutes/123 minutes/`. A more robust solution would be for panicparse to merge multiple values by replacing with `* minutes` (as with merged function params) or, if we want to be fancy, something like `(12-49) minutes`.

I wanted to bring these issues to your attention and see what you think a good solution might be. I'm not sure if, for other people in other contexts, having goroutines not be disambiguated for the above two reasons is useful. If so, perhaps there could be a flag for even more aggressive deduplication.

**Comment by maruel** [comment]
That's good ideas. For the first point, I'd be open for something like an --aggressive flag (or just -a).
For the second point, it's just that I hadn't experienced this, so I (or something else) can fix this.

**Comment by cespare** [comment]
@maruel thanks for the feedback. I'll send some PRs if I have time.

**Comment by maruel** [comment]
Reopening, since this issue is about two separate things, only the second part is fixed.

**Comment by maruel** [comment]
Implemented something that I think would be good. Sadly this is an API breaking change, which I forgot to note in the commit message, will do on my next push. I'm still relatively fine with breaking the API as in this case, fixing up is trivial. I didn't write tests yet.

@cespare does it looks good to you?

**Comment by cespare** [comment]
@maruel Thanks so much for implementing my suggestions! This is working really well.

One nitpick: if two blocked goroutines are merged that have been blocked for different amounts of time, right now the merging keeps the time from the first one. So if you have

```
goroutine 314279 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc82000a2c0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 314280 [select, 10000 minutes]:
net/http.(*persistConn).writeLoop(0xc82000a2c0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 314281 [select, 5 minutes]:
net/http.(*persistConn).writeLoop(0xc82000a2c0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
```

you get the output

```
3: select [3 minutes] [Created by http.(*Transport).dialConn @ transport.go:686]
    http transport.go:1009 (*persistConn).writeLoop(#1)
```

but the "3 minutes" part is misleading. It would be better to do this:

```
3: select [* minutes] [Created by http.(*Transport).dialConn @ transport.go:686]
    http transport.go:1009 (*persistConn).writeLoop(#1)
```

or this (more work):

```
3: select [3-10000 minutes] [Created by http.(*Transport).dialConn @ transport.go:686]
    http transport.go:1009 (*persistConn).writeLoop(#1)
```

**Comment by maruel** [comment]
Using a range is a great idea! Thanks, will look at this.

**Comment by cespare** [comment]
Awesome, thanks!

**Comment by maruel** [comment]
The refactoring was a bit invasive, please double check if you spot any regression. Thank for the suggestions.
